### ISSUE TITLE
dat clone http://eukaryota.dathub.org failing

### ISSUE THREAD

**Issue by ngoldman** [maxogden/dat#289]
I'm going through http://maxogden.github.io/get-dat/ and was able to clone http://eukaryota.dathub.org using the `try-dat` server, but was unable to clone on my local machine. I think everything's fine with my machine -- I updated node to latest patch of 0.10, and also tried with 0.12 and latest iojs for good measure. Same error message each time.

```
∴ ng@crimelab ~/dev/github $ node -v
v0.10.37
∴ ng@crimelab ~/dev/github $ npm -v
1.4.28
∴ ng@crimelab ~/dev/github $ dat version
dat version 6.9.7
∴ ng@crimelab ~/dev/github $ dat clone http://eukaryota.dathub.org eukaryota
Elapsed      : 1 s
Pulled       : 258.08 kB (172.06 kB/s)
 - changes : 943
 - blobs   : 0


TypeError: Cannot call method 'forEach' of undefined
    at compileMessage (/Users/ng/.nvm/v0.10.37/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:141:13)
    at resolve (/Users/ng/.nvm/v0.10.37/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:450:27)
    at /Users/ng/.nvm/v0.10.37/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:454:12
    at Array.map (native)
    at module.exports (/Users/ng/.nvm/v0.10.37/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:453:62)
    at new Messages (/Users/ng/.nvm/v0.10.37/lib/node_modules/dat/node_modules/protocol-buffers/index.js:15:5)
    at module.exports (/Users/ng/.nvm/v0.10.37/lib/node_modules/dat/node_modules/protocol-buffers/index.js:28:10)
    at Schema.compile (/Users/ng/.nvm/v0.10.37/lib/node_modules/dat/lib/schema.js:146:19)
    at null.<anonymous> (/Users/ng/.nvm/v0.10.37/lib/node_modules/dat/lib/commands.js:659:80)
    at emit (events.js:117:20)
```

**Comment by nylen** [comment]
I'm also experiencing a similar issue.  I was able to reproduce it on my machine by grabbing the `.dat` repository off of the `get-dat` server:

```sh
wget http://nylen.tv/dat/eukaryota.zip
aunpack eukaryota.zip
cd eukaryota/
dat cat  # or dat listen, or anything else
```

generates this error:

```
/usr/local/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:141
    m.oneof.forEach(function(o) {
            ^
TypeError: Cannot call method 'forEach' of undefined
    at compileMessage (/usr/local/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:141:13)
    at resolve (/usr/local/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:450:27)
    at /usr/local/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:454:12
    at Array.map (native)
    at module.exports (/usr/local/lib/node_modules/dat/node_modules/protocol-buffers/compile.js:453:62)
    at new Messages (/usr/local/lib/node_modules/dat/node_modules/protocol-buffers/index.js:15:5)
    at module.exports (/usr/local/lib/node_modules/dat/node_modules/protocol-buffers/index.js:28:10)
    at Schema.compile (/usr/local/lib/node_modules/dat/lib/schema.js:146:19)
    at /usr/local/lib/node_modules/dat/lib/schema.js:31:10
    at Function.<anonymous> (/usr/local/lib/node_modules/dat/node_modules/level-dat/index.js:445:5)
```

**Comment by karissa** [comment]
@maxogden is this fixed now that you updated it?

**Comment by maxogden** [comment]
just fixed it, it was running an older incompatible version of dat from
newer releases. i upgraded the server so it now works with dat >= v6

**Comment by karissa** [comment]
rad!

**Comment by ngoldman** [comment]
```
∴ ~/dev/lab $ node -v
v0.10.38
∴ ~/dev/lab $ npm -v
1.4.28
∴ ~/dev/lab $ dat version
dat version 6.9.7
∴ ~/dev/lab $ dat clone http://eukaryota.dathub.org eukaryota
Elapsed      : 3 s
Pulled       : 372.03 kB (93.01 kB/s)
 - changes : 1343
 - blobs   : 0

Clone from remote has completed.
```

![dancing-karate-guy](https://cloud.githubusercontent.com/assets/427322/6857993/22c1d6d6-d3c8-11e4-80bb-a40459b783c5.gif)

:+1:
