### ISSUE TITLE
dat write overwrites files in folder

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#395]
```
$ ls
package.json  data.dat  my_awesome_dataset.tar.gz 
$ dat write my_awesome_dataset.tar.gz
```

The link overwrites the original file. If you then try to `dat read`, you get an error:
```
$ dat read my_awesome_dataset.tar.gz --verbose
dat: Error reading my_awesome_dataset.tar.gz
NotFoundError: Key not found in database [files!tar.keys]
    at notFound (/Users/karissa/dev/node_modules/dat-core/index.js:309:10)
    at loop (/Users/karissa/dev/node_modules/dat-core/index.js:456:47)
    at Dat._getLayersPointer (/Users/karissa/dev/node_modules/dat-core/index.js:460:3)
    at /Users/karissa/dev/node_modules/dat-core/index.js:444:27
    at /Users/karissa/dev/node_modules/dat-core/index.js:436:5
    at f (/Users/karissa/dev/node_modules/dat-core/node_modules/stream-collector/node_modules/once/once.js:17:25)
    at ReadStream.<anonymous> (/Users/karissa/dev/node_modules/dat-core/node_modules/stream-collector/index.js:15:5)
    at ReadStream.emit (events.js:92:17)
    at /Users/karissa/dev/node_modules/dat-core/node_modules/levelup/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
```

**Comment by karissa** [comment]
somehow this was because I was on a fork, and each `write` created a fork. I'm not sure how to reproduce the initial state that was confusing, will close until then
