### ISSUE TITLE
TypeError: undefined is not a function when using `dat pull`

### ISSUE THREAD

**Issue by jeromew** [maxogden/dat#417]
For information, after a `dat pull http://npm.dathub.org`
I got
````
Pulled [+37, -0].
dat/node_modules/dat-core/lib/indexer.js:200
        if (log && samePath(log.split(':').slice(0, -1).join(':'), opts.path))
TypeError: undefined is not a function (shown on split)
    at /home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/lib/indexer.js:200:33
    at Object.cb (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7)
    at Array.<anonymous> (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/multileveldown/leveldown.js:88:9)
    at eval [as _decode] (eval at <anonymous> (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/pbs/node_modules/generate-function/index.js:55:21), <anonymous>:11:22)
    at Decoder._pushMessage (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/pbs/decoder.js:130:10)
    at Decoder._parseMissing (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/pbs/decoder.js:102:19)
    at Decoder._parse (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/pbs/decoder.js:143:23)
    at Decoder._write (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/pbs/decoder.js:193:10)
    at doWrite (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/pbs/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/u/.nvm/versions/node/v0.12.7/lib/node_modules/dat/node_modules/dat-core/node_modules/pbs/node_modules/readable-stream/lib/_stream_writable.js:266:5)
````

dat version is 7.1.2

**Comment by jeromew** [comment]
Apparently, in my install (leveldown 1.4.2), the log variable inside indexer.js is a Buffer.

I could fix the bug in `/dat-core/lib/indexer.js` by changing L202

     meta.get('log', function (err, log) {

     meta.get('log', {valueEncoding: 'utf-8'}, function (err, log) {

but I am far from sure that this is the correct fix here so i did not send a PR.

**Comment by karissa** [comment]
@jeromew if it fixes the bug, we'd merge it. However, we are starting to switch from beta to 1.0 and will be updating dat-core or replacing major parts of it with http://github.com/mafintosh/hyperdrive.

**Comment by karissa** [comment]
Apologies for the late response, we've been heads down working on this new version!

**Comment by jeromew** [comment]
ok thanks. do not worry on this it is not too much of a problem and I was just experimenting at this stage.
I'll try again when the big refectoring with hyperdrive is done.
Thanks for the pointer I'll look into hyperdrive it seems pretty interesting !
I'll close this ticket for now so you do not need to worry.
