### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by jeroenooms** [maxogden/dat#421]
Travis is reporting [unit tests failures](https://travis-ci.org/ropensci/rdat) for the `rdat` package which are caused by a problem in `dat push`:

```
> repo2$insert(cars[31:40,])
Wrote [+0, -0].
Wrote [+10, -0].
Done importing data. 
Version: 3ac0964f3a1e6ba6c710376c5f10096098d92f903405fe9166432102b9b336c2
> repo2$push()
Error: /home/travis/build/ropensci/dat/node_modules/dat-core/lib/indexer.js:200        if (log && samePath(log.split(':').slice(0, -1).join(':'), opts.path))                                ^TypeError: Object /tmp/RtmpKo4hhR/file62497360b7a2/data.dat:cihau4vl60000i5a9ey2qau4g has no method 'split'    at /home/travis/build/ropensci/dat/node_modules/dat-core/lib/indexer.js:200:33    at Object.cb (/home/travis/build/ropensci/dat/node_modules/dat-core/node_modules/subleveldown/node_modules/levelup/lib/levelup.js:230:7)    at Array.0 (/home/travis/build/ropensci/dat/node_modules/dat-core/node_modules/multileveldown/leveldown.js:88:9)    at eval [as _decode] (eval at <anonymous> (/home/travis/build/ropensci/dat/node_modules/dat-core/node_modules/pbs/node_modules/generate-function/index.js:55:21), <anonymous>:10:22)    at Decoder._pushMessage (/home/travis/build/ropensci/dat/node_modules/dat-core/node_modules/pbs/decoder.js:130:10)    at Decoder._parseMissing (/home/travis/build/ropensci/dat/
Execution halted
```

**Comment by karissa** [comment]
We're going to have to deprecate the R package because we made a pivot from beta to 1.0. Rationale will be up on https://vimeo.com/channels/rocommunitycalls.. I promise, it's going to be good!

**Comment by karissa** [comment]
Added a notice to rdat

**Comment by jeroenooms** [comment]
Deprecate? You mean like some API changes?
