### ISSUE TITLE
EventEmitter memory leak due to too many listeners

### ISSUE THREAD

**Issue by karissa** [maxogden/dat#427]
got this testing 1.0, what should the max limit be?
```
(node) warning: possible EventEmitter memory leak detected. 11 peer listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at /Users/karissa/dev/node_modules/dat/node_modules/discovery-channel/index.js:35:13
    at Array.forEach (native)
    at Object.lookup (/Users/karissa/dev/node_modules/dat/node_modules/discovery-channel/index.js:33:10)
    at update [as _repeat] (/Users/karissa/dev/node_modules/dat/index.js:72:35)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
(node) warning: possible EventEmitter memory leak detected. 11 peer listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at /Users/karissa/dev/node_modules/dat/node_modules/discovery-channel/index.js:35:13
    at Array.forEach (native)
    at Object.lookup (/Users/karissa/dev/node_modules/dat/node_modules/discovery-channel/index.js:33:10)
    at update [as _repeat] (/Users/karissa/dev/node_modules/dat/index.js:72:35)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by onbjerg** [comment]
how many do you need?

**Comment by mafintosh** [comment]
pretty sure this is fixed now after we upgraded discovery-channel.
