### ISSUE TITLE
what ports need to be open for `dat link`?

### ISSUE THREAD

**Issue by beaugunderson** [maxogden/dat#428]
I ran `dat link` in a directory on one computer and `dat dat://75d3160480a9229dd0102f4803f3b7c6601853e8bc810d54a74826cff94ad24a` on another and nothing seemed to happen other than an eventual EventEmitter link:

```
Downloading...
(node) warning: possible EventEmitter memory leak detected. 11 peer listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at /Users/beau/p/dat/node_modules/discovery-channel/index.js:35:13
    at Array.forEach (native)
    at Object.lookup (/Users/beau/p/dat/node_modules/discovery-channel/index.js:33:10)
    at update [as _repeat] (/Users/beau/p/dat/index.js:77:35)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
(node) warning: possible EventEmitter memory leak detected. 11 peer listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:239:17)
    at /Users/beau/p/dat/node_modules/discovery-channel/index.js:35:13
    at Array.forEach (native)
    at Object.lookup (/Users/beau/p/dat/node_modules/discovery-channel/index.js:33:10)
    at update [as _repeat] (/Users/beau/p/dat/index.js:77:35)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)
```

leading me to believe that maybe the correct ports on the first computer aren't open.

**Comment by maxogden** [comment]
@beaugunderson sorry about that nasty output, we're working on fixing it. Latest master will try to use port 3282 (DATA on a phone keypad). I'll try to improve the debuggability of this kind of thing as well

**Comment by karissa** [comment]
This is now displaying the port the server is using in the terminal now
