### ISSUE TITLE
Dat crashes on empty files

### ISSUE THREAD

**Issue by paulkernfeld** [maxogden/dat#431]
For me, dat seems to crash when trying to clone a directory that has any files of length zero.

I created files with this script:
```bash
mkdir up
echo "meow" > up/full.txt
touch up/empty.txt
cd up
dat link
```

And I tried to download them with this script (using the hash from the first script, I think your hash will be different if you're trying to reproduce the bug):
```bash
mkdir down
cd down
dat c373e3dc3479bedc156bb37b2bf29fd79d9d751fd702349831643e0144781a62
```

And I got this error:
```
Downloading...
buffer.js:595
        return this.utf8Write(string, offset, length);
                    ^

TypeError: Argument must be a string
    at TypeError (native)
    at Buffer.write (buffer.js:595:21)
    at Object.exports.bytes.encode (/Users/paul/repos/hyperdrive/node_modules/protocol-buffers/encodings.js:35:17)
    at Object.encode (eval at <anonymous> (/Users/paul/repos/hyperdrive/node_modules/generate-function/index.js:55:21), <anonymous>:13:10)
    at Protocol._push (/Users/paul/repos/hyperdrive/lib/protocol.js:290:7)
    at Protocol.join (/Users/paul/repos/hyperdrive/lib/protocol.js:302:8)
    at Swarm.join (/Users/paul/repos/hyperdrive/lib/swarm.js:134:19)
    at new Feed (/Users/paul/repos/hyperdrive/lib/feed.js:24:37)
    at Feed (/Users/paul/repos/hyperdrive/lib/feed.js:11:39)
    at Hyperdrive.get (/Users/paul/repos/hyperdrive/index.js:42:10)
```

**Comment by karissa** [comment]
Ah, nice catch @paulkernfeld.

@mafintosh I think the hyperdrive API is confusing on this bit. 
```js
var feed = drive.get(link)
var content = drive.get(feed) // throws error
var contentStream = content.createStream()
```

Do you have an idea of how we can have `drive` or `feed` know how to get the content stream, empty or not? 

It'd be nice to avoid overloading `drive.get` if we can get away with it

**Comment by mafintosh** [comment]
@karissa i agree. i'm gonna change after we do an initial release
